/* Generated By:JJTree&JavaCC: Do not edit this line. StringMathParserConstants.java */
package org.clematis.math.reference.parser.string;

public interface StringMathParserConstants {

  int EOF = 0;
  int NUMBER = 7;
  int INTEGER = 8;
  int FLOAT = 9;
  int EXPONENT = 10;
  int IDENTIFIER = 11;
  int LETTER = 12;
  int VARIABLE = 13;
  int PI = 14;
  int MULT = 15;
  int DIV = 16;
  int PLUS = 17;
  int MINUS = 18;
  int EQUALS = 19;
  int POWER = 20;
  int OPEN_BR = 21;
  int CLOSE_BR = 22;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<NUMBER>",
    "<INTEGER>",
    "<FLOAT>",
    "<EXPONENT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<VARIABLE>",
    "\"pi\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\"^\"",
    "<OPEN_BR>",
    "<CLOSE_BR>",
    "\"sin\"",
    "\"arcsin\"",
    "\"cos\"",
    "\"arccos\"",
    "\"tan\"",
    "\"arctan\"",
    "\"sec\"",
    "\"csc\"",
    "\"cot\"",
    "\"exp\"",
    "\"sqrt\"",
    "\"ln\"",
    "\"lg\"",
    "\"log\"",
    "\"fact\"",
    "\"arccot\"",
    "\"arcsec\"",
    "\"arccsc\"",
    "\"abs\"",
    "\"sinh\"",
    "\"arcsinh\"",
    "\"cosh\"",
    "\"arccosh\"",
    "\"tanh\"",
    "\"arctanh\"",
    "\"coth\"",
    "\"arccoth\"",
    "\"sech\"",
    "\"arcsech\"",
    "\"csch\"",
    "\"arccsch\"",
  };

}
