/* Generated By:JJTree: Do not edit this line. StringMathParserTreeConstants.java */

package org.clematis.math.reference.parser.string;

public interface StringMathParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTEXPR = 1;
  public int JJTPLUS_EXPR = 2;
  public int JJTMINUS_EXPR = 3;
  public int JJTMULT_EXPR = 4;
  public int JJTDIV_EXPR = 5;
  public int JJTUNARY_MINUS = 6;
  public int JJTPOWER_EXPR = 7;
  public int JJTBR_EXPR = 8;
  public int JJTVAR = 9;
  public int JJTNUMBER = 10;
  public int JJTIDENTIFIER = 11;
  public int JJTPI = 12;
  public int JJTOPEN_BR = 13;
  public int JJTCLOSE_BR = 14;
  public int JJTFUNCTION = 15;
  public int JJTARG = 16;


  public String[] jjtNodeName = {
    "void",
    "EXPR",
    "PLUS_EXPR",
    "MINUS_EXPR",
    "MULT_EXPR",
    "DIV_EXPR",
    "UNARY_MINUS",
    "POWER_EXPR",
    "BR_EXPR",
    "VAR",
    "NUMBER",
    "IDENTIFIER",
    "PI",
    "OPEN_BR",
    "CLOSE_BR",
    "FUNCTION",
    "ARG",
  };
}
