/* Generated By: webtex.jjt,v 1.6 2005/04/21 13&JJTree: Do not edit this line. WebTexParserTreeConstants.java */

package org.clematis.math.reference.parser.webtex;

public interface WebTexParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTEXPR = 1;
  public int JJTEQUALS_EXPR = 2;
  public int JJTPLUS_EXPR = 3;
  public int JJTMINUS_EXPR = 4;
  public int JJTMULT_EXPR = 5;
  public int JJTDIV_EXPR = 6;
  public int JJTUNARY_MINUS = 7;
  public int JJTPOWER_EXPR = 8;
  public int JJTINDEX_EXPR = 9;
  public int JJTVAR = 10;
  public int JJTNUMBER = 11;
  public int JJTCONSTANT = 12;
  public int JJTFUNCTION = 13;
  public int JJTARG = 14;


  public String[] jjtNodeName = {
    "void",
    "EXPR",
    "EQUALS_EXPR",
    "PLUS_EXPR",
    "MINUS_EXPR",
    "MULT_EXPR",
    "DIV_EXPR",
    "UNARY_MINUS",
    "POWER_EXPR",
    "INDEX_EXPR",
    "VAR",
    "NUMBER",
    "CONSTANT",
    "FUNCTION",
    "ARG",
  };
}
