/* Generated By:JJTree: Do not edit this line. StringMathParserTreeConstants.java */

package org.clematis.math.v1.parser.string;

public interface StringMathParserTreeConstants {
    int JJTVOID = 0;
    int JJTEXPR = 1;
    int JJTPLUS_EXPR = 2;
    int JJTMINUS_EXPR = 3;
    int JJTMULT_EXPR = 4;
    int JJTDIV_EXPR = 5;
    int JJTUNARY_MINUS = 6;
    int JJTPOWER_EXPR = 7;
    int JJTBR_EXPR = 8;
    int JJTVAR = 9;
    int JJTNUMBER = 10;
    int JJTIDENTIFIER = 11;
    int JJTPI = 12;
    int JJTOPEN_BR = 13;
    int JJTCLOSE_BR = 14;
    int JJTFUNCTION = 15;
    int JJTARG = 16;


    String[] jjtNodeName = {
        "void",
        "EXPR",
        "PLUS_EXPR",
        "MINUS_EXPR",
        "MULT_EXPR",
        "DIV_EXPR",
        "UNARY_MINUS",
        "POWER_EXPR",
        "BR_EXPR",
        "VAR",
        "NUMBER",
        "IDENTIFIER",
        "PI",
        "OPEN_BR",
        "CLOSE_BR",
        "FUNCTION",
        "ARG",
    };
}
