/* Generated By: webtex.jjt,v 1.6 2005/04/21 13&JJTree: Do not edit this line. WebTexParserTreeConstants.java */

package org.clematis.math.v1.parser.webtex;

public interface WebTexParserTreeConstants {
    int JJTVOID = 0;
    int JJTEXPR = 1;
    int JJTEQUALS_EXPR = 2;
    int JJTPLUS_EXPR = 3;
    int JJTMINUS_EXPR = 4;
    int JJTMULT_EXPR = 5;
    int JJTDIV_EXPR = 6;
    int JJTUNARY_MINUS = 7;
    int JJTPOWER_EXPR = 8;
    int JJTINDEX_EXPR = 9;
    int JJTVAR = 10;
    int JJTNUMBER = 11;
    int JJTCONSTANT = 12;
    int JJTFUNCTION = 13;
    int JJTARG = 14;


    String[] jjtNodeName = {
        "void",
        "EXPR",
        "EQUALS_EXPR",
        "PLUS_EXPR",
        "MINUS_EXPR",
        "MULT_EXPR",
        "DIV_EXPR",
        "UNARY_MINUS",
        "POWER_EXPR",
        "INDEX_EXPR",
        "VAR",
        "NUMBER",
        "CONSTANT",
        "FUNCTION",
        "ARG",
    };
}
