/* Generated By: webtex.jjt,v 1.6 2005/04/21 13&JJTree&JavaCC: Do not edit this line. WebTexParserConstants.java */
package org.clematis.math.v1.parser.webtex;

public interface WebTexParserConstants {

    int EOF = 0;
    int NUMBER = 7;
    int INTEGER = 8;
    int FLOAT = 9;
    int EXPONENT = 10;
    int IDENTIFIER = 11;
    int LETTER = 12;
    int PI = 13;
    int EXP_E = 14;
    int MULT = 15;
    int DIV = 16;
    int PLUS = 17;
    int MINUS = 18;
    int EQUALS = 19;

    int DEFAULT = 0;

    String[] tokenImage = {
        "<EOF>",
        "\" \"",
        "\"\\t\"",
        "\"\\n\"",
        "\"\\r\"",
        "<token of kind 5>",
        "<token of kind 6>",
        "<NUMBER>",
        "<INTEGER>",
        "<FLOAT>",
        "<EXPONENT>",
        "<IDENTIFIER>",
        "<LETTER>",
        "\"\\\\pi\"",
        "\"e\"",
        "<MULT>",
        "<DIV>",
        "\"+\"",
        "\"-\"",
        "\"=\"",
        "\"^\"",
        "\"_\"",
        "\"(\"",
        "\")\"",
        "\"{\"",
        "\"}\"",
        "\"[\"",
        "\"]\"",
        "\"\\\\frac\"",
        "\"\\\\sin\"",
        "\"\\\\arcsin\"",
        "\"\\\\cos\"",
        "\"\\\\arccos\"",
        "\"\\\\tan\"",
        "\"\\\\arctan\"",
        "\"\\\\sec\"",
        "\"\\\\csc\"",
        "\"\\\\cot\"",
        "\"\\\\exp\"",
        "\"\\\\sqrt\"",
        "\"\\\\root\"",
        "\"\\\\ln\"",
        "\"\\\\lg\"",
        "\"\\\\log\"",
    };

}
