/* Generated By:JJTree: Do not edit this line. ..\StringMathParserTreeConstants.java */

package org.clematis.math.parsers;

public interface StringMathParserTreeConstants {
    int JJTVOID = 0;
    int JJTEXPR = 1;
    int JJTEQUALS_EXPR = 2;
    int JJTPLUS_EXPR = 3;
    int JJTMINUS_EXPR = 4;
    int JJTMULT_EXPR = 5;
    int JJTDIV_EXPR = 6;
    int JJTUNARY_MINUS = 7;
    int JJTUNARY_PLUS = 8;
    int JJTPOWER_EXPR = 9;
    int JJTINDEX_EXPR = 10;
    int JJTINDEX = 11;
    int JJTSTRING = 12;
    int JJTVAR = 13;
    int JJTNUMBER = 14;
    int JJTIDENTIFIER = 15;
    int JJTCONSTANT = 16;
    int JJTDELTA_EXPR = 17;
    int JJTHAT_EXPR = 18;
    int JJTVECTOR_EXPR = 19;
    int JJTFUNCTION = 20;


    String[] jjtNodeName = {
        "void",
        "EXPR",
        "EQUALS_EXPR",
        "PLUS_EXPR",
        "MINUS_EXPR",
        "MULT_EXPR",
        "DIV_EXPR",
        "UNARY_MINUS",
        "UNARY_PLUS",
        "POWER_EXPR",
        "INDEX_EXPR",
        "INDEX",
        "STRING",
        "VAR",
        "NUMBER",
        "IDENTIFIER",
        "CONSTANT",
        "DELTA_EXPR",
        "HAT_EXPR",
        "VECTOR_EXPR",
        "FUNCTION",
    };
}
