/* Generated By:JJTree: Do not edit this line. ..\StringMathParserVisitor.java */

package org.clematis.math.parsers;

public interface StringMathParserVisitor {
    Object visit(SimpleNode node, Object data);
}
