/* Generated By:JJTree: Do not edit this line. ..\WebTexParserVisitor.java */

package org.clematis.math.parsers;

public interface WebTexParserVisitor {
    Object visit(SimpleNode node, Object data);
}
