/* Generated By:JJTree&JavaCC: Do not edit this line. WebTexParserConstants.java */
package org.clematis.math.v2.parsers.webtex;

public interface WebTexParserConstants {

    int EOF = 0;
    int NUMBER = 7;
    int INTEGER = 8;
    int FLOAT = 9;
    int EXPONENT = 10;
    int IDENTIFIER = 11;
    int LETTER = 12;
    int VARIABLE = 13;
    int STRING = 14;
    int EXP_E = 15;
    int PI = 16;
    int MULT = 17;
    int DIV = 18;
    int PLUS = 19;
    int MINUS = 20;
    int EQUALS = 21;
    int POWER = 22;
    int DELTA = 23;
    int HAT = 24;
    int OPEN_BR = 25;
    int CLOSE_BR = 26;
    int UNDERLINE = 27;

    int DEFAULT = 0;

    String[] tokenImage = {
        "<EOF>",
        "\" \"",
        "\"\\t\"",
        "\"\\n\"",
        "\"\\r\"",
        "<token of kind 5>",
        "<token of kind 6>",
        "<NUMBER>",
        "<INTEGER>",
        "<FLOAT>",
        "<EXPONENT>",
        "<IDENTIFIER>",
        "<LETTER>",
        "<VARIABLE>",
        "<STRING>",
        "\"e\"",
        "<PI>",
        "<MULT>",
        "<DIV>",
        "\"+\"",
        "\"-\"",
        "\"=\"",
        "\"^\"",
        "<DELTA>",
        "<HAT>",
        "<OPEN_BR>",
        "<CLOSE_BR>",
        "\"_\"",
        "\"\\\\vec\"",
        "\"vec\"",
        "\"\\\\\"",
    };

}
